create extension if not exists "pgcrypto";

create table if not exists clientes (
  id uuid primary key default gen_random_uuid(),
  nome text not null,
  nome_fantasia text,
  cpf_cnpj text,
  telefone text,
  whatsapp text,
  email text,
  observacoes text,
  ativo boolean not null default true,
  created_at timestamptz not null default now()
);

create table if not exists locais (
  id uuid primary key default gen_random_uuid(),
  cliente_id uuid not null references clientes(id) on delete cascade,
  nome text not null,
  endereco text,
  numero text,
  complemento text,
  bairro text,
  cidade text,
  estado text,
  cep text,
  referencia text,
  observacoes text,
  created_at timestamptz not null default now()
);

create table if not exists equipamentos (
  id uuid primary key default gen_random_uuid(),
  cliente_id uuid not null references clientes(id) on delete cascade,
  local_id uuid references locais(id) on delete set null,
  ambiente text,
  tipo text,
  marca text,
  modelo text,
  numero_serie text,
  capacidade_btu integer,
  refrigerante text,
  tensao text,
  data_instalacao date,
  patrimonio text,
  observacoes text,
  ativo boolean not null default true,
  created_at timestamptz not null default now()
);

create type chamado_status as enum (
  'aberto',
  'agendado',
  'em_atendimento',
  'concluido',
  'cancelado'
);

create table if not exists chamados (
  id uuid primary key default gen_random_uuid(),
  numero bigint generated by default as identity unique,
  cliente_id uuid not null references clientes(id),
  local_id uuid references locais(id),
  equipamento_id uuid references equipamentos(id),
  descricao text not null,
  tipo_servico text not null,
  prioridade text not null default 'normal',
  status chamado_status not null default 'aberto',
  data_agendada date,
  hora_agendada time,
  duracao_prevista_min integer,
  tecnico text,
  observacoes text,
  created_at timestamptz not null default now()
);

create type os_status as enum (
  'rascunho',
  'em_atendimento',
  'pausada',
  'aguardando_conclusao',
  'concluida',
  'cancelada'
);

create table if not exists ordens_servico (
  id uuid primary key default gen_random_uuid(),
  numero bigint generated by default as identity unique,
  chamado_id uuid references chamados(id),
  cliente_id uuid not null references clientes(id),
  local_id uuid references locais(id),
  equipamento_id uuid references equipamentos(id),
  tecnico text,
  inicio timestamptz,
  termino timestamptz,
  diagnostico text,
  servico_executado text,
  situacao_final text,
  recomendacoes text,
  pendencias text,
  observacoes text,
  valor_servico numeric(12,2),
  forma_pagamento text,
  status os_status not null default 'rascunho',
  created_at timestamptz not null default now()
);

create table if not exists checklist_itens (
  id uuid primary key default gen_random_uuid(),
  os_id uuid not null references ordens_servico(id) on delete cascade,
  categoria text,
  item text not null,
  status text,
  observacao text,
  foto_url text
);

create table if not exists medicoes (
  id uuid primary key default gen_random_uuid(),
  os_id uuid not null references ordens_servico(id) on delete cascade,
  retorno_c numeric,
  insuflamento_c numeric,
  delta_t_c numeric,
  externa_c numeric,
  tensao_v numeric,
  corrente_a numeric,
  frequencia_hz numeric,
  pressao_succao numeric,
  pressao_descarga numeric,
  superaquecimento_c numeric,
  subresfriamento_c numeric,
  refrigerante text,
  observacoes text
);

create table if not exists materiais (
  id uuid primary key default gen_random_uuid(),
  os_id uuid not null references ordens_servico(id) on delete cascade,
  descricao text not null,
  quantidade numeric(12,2) not null default 1,
  unidade text,
  valor_unitario numeric(12,2),
  valor_total numeric(12,2)
);

create table if not exists fotos_servico (
  id uuid primary key default gen_random_uuid(),
  os_id uuid not null references ordens_servico(id) on delete cascade,
  tipo text not null,
  url text not null,
  legenda text,
  created_at timestamptz not null default now()
);

create table if not exists assinaturas (
  id uuid primary key default gen_random_uuid(),
  os_id uuid not null references ordens_servico(id) on delete cascade,
  nome_tecnico text,
  nome_cliente text,
  assinatura_tecnico_url text,
  assinatura_cliente_url text,
  created_at timestamptz not null default now()
);

create table if not exists relatorios (
  id uuid primary key default gen_random_uuid(),
  os_id uuid not null references ordens_servico(id) on delete cascade,
  arquivo_url text,
  enviado boolean not null default false,
  enviado_em timestamptz,
  created_at timestamptz not null default now()
);


-- Segurança mínima para quando autenticação for ativada.
-- Antes de produção multiusuário, habilite RLS e políticas por usuário/empresa.
-- O MVP local-first funciona sem estas políticas até a conexão em nuvem ser configurada.

create table if not exists orcamentos (
  id uuid primary key default gen_random_uuid(),
  cliente_id uuid not null references clientes(id),
  descricao text not null,
  valor numeric(12,2) not null default 0,
  status text not null default 'Rascunho',
  created_at timestamptz not null default now()
);
