"use client"; import {FormEvent,useEffect,useState} from "react"; import {useParams,useRouter} from "next/navigation"; import {getSupabase} from "@/lib/supabase";
export default function NovoEq(){const {id}=useParams<{id:string}>();const r=useRouter();const [erro,setErro]=useState("");const [locais,setLocais]=useState<any[]>([]);const [f,setF]=useState({local_id:"",ambiente:"",tipo:"Split Hi-Wall",marca:"",modelo:"",numero_serie:"",capacidade_btu:"",refrigerante:"",tensao:"220 V",patrimonio:"",observacoes:""});
useEffect(()=>{const s=getSupabase();if(!s)return;s.from("locais").select("id,nome").eq("cliente_id",id).order("nome").then(({data})=>setLocais(data||[]))},[id]);
async function save(e:FormEvent){e.preventDefault();if(!f.ambiente)return;const s=getSupabase();if(!s)return setErro("Supabase não configurado.");const {error}=await s.from("equipamentos").insert({cliente_id:id,local_id:f.local_id||null,ambiente:f.ambiente,tipo:f.tipo,marca:f.marca||null,modelo:f.modelo||null,numero_serie:f.numero_serie||null,capacidade_btu:f.capacidade_btu?Number(f.capacidade_btu):null,refrigerante:f.refrigerante||null,tensao:f.tensao||null,patrimonio:f.patrimonio||null,observacoes:f.observacoes||null,ativo:true});if(error)return setErro(error.message);r.push(`/clientes/${id}`);r.refresh()}
return <div className="page"><header className="simple-header"><div><p className="eyebrow">EQUIPAMENTO</p><h1>Novo equipamento</h1></div></header><form className="form-card" onSubmit={save}>
<div className="field"><label>Local</label><select value={f.local_id} onChange={e=>setF({...f,local_id:e.target.value})}><option value="">Sem local</option>{locais.map(x=><option key={x.id} value={x.id}>{x.nome}</option>)}</select></div>
<div className="field"><label>Ambiente *</label><input value={f.ambiente} onChange={e=>setF({...f,ambiente:e.target.value})}/></div>
<div className="field-grid"><div className="field"><label>Tipo</label><select value={f.tipo} onChange={e=>setF({...f,tipo:e.target.value})}><option>Split Hi-Wall</option><option>Split Piso-Teto</option><option>Cassete</option><option>Janela</option><option>VRF/VRV</option><option>Outro</option></select></div><div className="field"><label>Capacidade BTU</label><input type="number" value={f.capacidade_btu} onChange={e=>setF({...f,capacidade_btu:e.target.value})}/></div></div>
{["marca","modelo","numero_serie","patrimonio"].map(k=><div className="field" key={k}><label>{({marca:"Marca",modelo:"Modelo",numero_serie:"Número de série",patrimonio:"Patrimônio / ID"} as any)[k]}</label><input value={(f as any)[k]} onChange={e=>setF({...f,[k]:e.target.value})}/></div>)}
<div className="field-grid"><div className="field"><label>Refrigerante</label><select value={f.refrigerante} onChange={e=>setF({...f,refrigerante:e.target.value})}><option value="">Selecione</option><option>R-22</option><option>R-410A</option><option>R-32</option><option>Outro</option></select></div><div className="field"><label>Tensão</label><select value={f.tensao} onChange={e=>setF({...f,tensao:e.target.value})}><option>127 V</option><option>220 V</option><option>380 V</option></select></div></div>
<div className="field"><label>Observações</label><textarea rows={3} value={f.observacoes} onChange={e=>setF({...f,observacoes:e.target.value})}/></div>
{erro&&<div className="error-box">{erro}</div>}<div className="form-actions"><button type="button" className="secondary-button" onClick={()=>r.back()}>Cancelar</button><button className="primary-button">Salvar equipamento</button></div></form></div>}
