"use client";
import {useEffect,useMemo,useState} from "react"; import {useParams,useRouter} from "next/navigation"; import {CHECKLIST_PREVENTIVA,moeda} from "@/lib/domain"; import {addStore,readStore,updateStore} from "@/lib/local-store";
export default function OSPage(){const {id}=useParams<{id:string}>();const r=useRouter();const [os,setOs]=useState<any>();const [cliente,setCliente]=useState<any>();const [eq,setEq]=useState<any>();const [tab,setTab]=useState("diagnostico");const [check,setCheck]=useState<any[]>([]);const [med,setMed]=useState<any>({retorno:"",insuflamento:"",tensao:"",corrente:"",pressao_succao:"",pressao_descarga:"",superaquecimento:"",subresfriamento:"",observacoes:""});const [material,setMaterial]=useState({descricao:"",quantidade:"1",valor_unitario:""});const [mats,setMats]=useState<any[]>([]);const [assinatura,setAssinatura]=useState("");
useEffect(()=>{const o=readStore<any>("ordens").find(x=>x.id===id);setOs(o);if(o){setCliente(readStore<any>("clientes").find(x=>x.id===o.cliente_id));setEq(readStore<any>("equipamentos").find(x=>x.id===o.equipamento_id));const existing=readStore<any>("checklists").filter(x=>x.os_id===id);setCheck(existing.length?existing:CHECKLIST_PREVENTIVA.map(([categoria,item])=>({id:crypto.randomUUID(),os_id:id,categoria,item,status:"",observacao:""})));setMats(readStore<any>("materiais").filter(x=>x.os_id===id));const mm=readStore<any>("medicoes").find(x=>x.os_id===id);if(mm)setMed(mm)}},[id]);
const delta=useMemo(()=>med.retorno&&med.insuflamento?(Number(med.retorno)-Number(med.insuflamento)).toFixed(1):"—",[med.retorno,med.insuflamento]);
if(!os)return <div className="page">Carregando OS...</div>;
function saveOS(next:any=os){updateStore("ordens",next);setOs(next)}
function saveChecklist(){const all=readStore<any>("checklists").filter(x=>x.os_id!==id);localStorage.setItem("rmassist_checklists",JSON.stringify([...check,...all]));}
function saveMed(){const item={...med,id:med.id||crypto.randomUUID(),os_id:id,delta_t:delta};const all=readStore<any>("medicoes").filter(x=>x.os_id!==id);localStorage.setItem("rmassist_medicoes",JSON.stringify([item,...all]));setMed(item)}
function addMat(){if(!material.descricao)return;const m={...material,id:crypto.randomUUID(),os_id:id,quantidade:Number(material.quantidade),valor_unitario:Number(material.valor_unitario||0),valor_total:Number(material.quantidade)*Number(material.valor_unitario||0)};addStore("materiais",m);setMats([m,...mats]);setMaterial({descricao:"",quantidade:"1",valor_unitario:""})}
function finalizar(){const next={...os,status:"concluida",termino:new Date().toISOString()};saveOS(next);const chamados=readStore<any>("chamados");const c=chamados.find(x=>x.id===os.chamado_id);if(c)updateStore("chamados",{...c,status:"concluido"});if(assinatura)addStore("assinaturas",{id:crypto.randomUUID(),os_id:id,nome_cliente:assinatura,created_at:new Date().toISOString()});r.push(`/os/${id}/relatorio`)}
return <div className="page"><header className="simple-header"><div><p className="eyebrow">ORDEM DE SERVIÇO</p><h1>OS #{String(os.numero).padStart(4,"0")}</h1><p>{cliente?.nome_fantasia||cliente?.nome} • {eq?.ambiente||os.tipo_servico}</p></div><span className={`status-chip ${os.status}`}>{os.status.replace("_"," ")}</span></header>
<div className="step-tabs">{[["diagnostico","Diagnóstico"],["checklist","Checklist"],["medicoes","Medições"],["execucao","Execução"],["conclusao","Conclusão"]].map(([k,l])=><button className={tab===k?"active":""} onClick={()=>setTab(k)} key={k}>{l}</button>)}</div>
{tab==="diagnostico"&&<section className="form-card"><h3>Diagnóstico inicial</h3><div className="field"><label>Diagnóstico / condição encontrada</label><textarea rows={6} value={os.diagnostico||""} onChange={e=>saveOS({...os,diagnostico:e.target.value})}/></div><div className="photo-input"><label>Adicionar foto</label><input type="file" accept="image/*" capture="environment"/></div></section>}
{tab==="checklist"&&<section className="form-card"><h3>Checklist de manutenção</h3><div className="check-list">{check.map((x,i)=><div className="check-row" key={x.id}><div><strong>{x.item}</strong><small>{x.categoria}</small></div><select value={x.status} onChange={e=>{const a=[...check];a[i]={...x,status:e.target.value};setCheck(a)}}><option value="">Selecionar</option><option value="conforme">Conforme</option><option value="nao_conforme">Não conforme</option><option value="na">N/A</option></select></div>)}</div><button className="primary-button" onClick={saveChecklist}>Salvar checklist</button></section>}
{tab==="medicoes"&&<section className="form-card"><h3>Medições técnicas</h3><div className="measure-grid">{[["retorno","Retorno °C"],["insuflamento","Insuflamento °C"],["tensao","Tensão V"],["corrente","Corrente A"],["pressao_succao","Sucção"],["pressao_descarga","Descarga"],["superaquecimento","Superaquecimento °C"],["subresfriamento","Sub-resfriamento °C"]].map(([k,l])=><div className="field" key={k}><label>{l}</label><input inputMode="decimal" value={med[k]||""} onChange={e=>setMed({...med,[k]:e.target.value})}/></div>)}</div><div className="delta-card">ΔT calculado: <strong>{delta} °C</strong></div><div className="field"><label>Observações</label><textarea rows={3} value={med.observacoes||""} onChange={e=>setMed({...med,observacoes:e.target.value})}/></div><button className="primary-button" onClick={saveMed}>Salvar medições</button></section>}
{tab==="execucao"&&<section className="form-card"><h3>Execução do serviço</h3><div className="field"><label>Serviço executado</label><textarea rows={6} value={os.servico_executado||""} onChange={e=>saveOS({...os,servico_executado:e.target.value})}/></div><h3 className="form-section-title">Materiais / peças</h3><div className="field-grid"><div className="field"><label>Descrição</label><input value={material.descricao} onChange={e=>setMaterial({...material,descricao:e.target.value})}/></div><div className="field"><label>Quantidade</label><input type="number" value={material.quantidade} onChange={e=>setMaterial({...material,quantidade:e.target.value})}/></div></div><div className="field"><label>Valor unitário</label><input inputMode="decimal" value={material.valor_unitario} onChange={e=>setMaterial({...material,valor_unitario:e.target.value})}/></div><button type="button" className="secondary-button" onClick={addMat}>+ Adicionar material</button>{mats.map(m=><div className="material-line" key={m.id}><span>{m.quantidade} × {m.descricao}</span><strong>{moeda(m.valor_total)}</strong></div>)}<div className="field"><label>Recomendações</label><textarea rows={3} value={os.recomendacoes||""} onChange={e=>saveOS({...os,recomendacoes:e.target.value})}/></div><div className="photo-input"><label>Fotos antes / durante / depois</label><input type="file" accept="image/*" capture="environment" multiple/></div></section>}
{tab==="conclusao"&&<section className="form-card"><h3>Conclusão</h3><div className="field"><label>Situação final do equipamento</label><select value={os.situacao_final||""} onChange={e=>saveOS({...os,situacao_final:e.target.value})}><option value="">Selecione</option><option>Operando normalmente</option><option>Operando com ressalvas</option><option>Equipamento parado</option><option>Aguardando peça / retorno</option></select></div><div className="field"><label>Pendências</label><textarea rows={3} value={os.pendencias||""} onChange={e=>saveOS({...os,pendencias:e.target.value})}/></div><div className="field-grid"><div className="field"><label>Valor do serviço (R$)</label><input inputMode="decimal" value={os.valor_servico||""} onChange={e=>saveOS({...os,valor_servico:e.target.value})}/></div><div className="field"><label>Forma de pagamento</label><select value={os.forma_pagamento||""} onChange={e=>saveOS({...os,forma_pagamento:e.target.value})}><option value="">Selecione</option><option>PIX</option><option>Dinheiro</option><option>Cartão</option><option>Boleto</option><option>Faturado</option></select></div></div><div className="field"><label>Responsável pelo cliente / aceite</label><input value={assinatura} onChange={e=>setAssinatura(e.target.value)} placeholder="Nome de quem acompanhou o serviço"/></div><button className="primary-button full-button" onClick={finalizar}>Finalizar OS e gerar relatório</button></section>}
</div>}
