"use client"; import Image from "next/image"; import Link from "next/link"; import {useEffect,useState} from "react"; import {readStore} from "@/lib/local-store";
export default function Home(){const [s,setS]=useState({hoje:0,abertos:0,andamento:0,clientes:0});const [agenda,setAgenda]=useState<any[]>([]);const [cs,setCs]=useState<any[]>([]);
useEffect(()=>{const ch=readStore<any>("chamados"),os=readStore<any>("ordens"),c=readStore<any>("clientes");const hoje=new Date().toISOString().slice(0,10);setS({hoje:ch.filter(x=>x.data_agendada===hoje).length,abertos:ch.filter(x=>["aberto","agendado"].includes(x.status)).length,andamento:os.filter(x=>x.status==="em_atendimento").length,clientes:c.length});setAgenda(ch.filter(x=>x.data_agendada).sort((a,b)=>(a.data_agendada+a.hora_agendada).localeCompare(b.data_agendada+b.hora_agendada)).slice(0,3));setCs(c)},[]);
const nome=(id:string)=>{const c=cs.find(x=>x.id===id);return c?.nome_fantasia||c?.nome||"Cliente"};
return <div className="page"><header className="topbar"><div className="brand"><Image src="/icons/rm-assist-logo.png" alt="RM Assist" width={50} height={50} className="brand-logo"/><div><h1>RM Assist</h1><p>Gestão de serviços</p></div></div><span>🔔</span></header>
<section className="hero"><div><p className="eyebrow">PAINEL</p><h2>Bom dia!</h2><p>Seus atendimentos em um só lugar.</p></div><Link href="/chamados/novo" className="primary-button">+ Novo chamado</Link></section>
<div className="stat-grid">{[[s.hoje,"Serviços hoje"],[s.abertos,"Chamados abertos"],[s.andamento,"OS em andamento"],[s.clientes,"Clientes"]].map(([v,l])=><article className="stat-card" key={String(l)}><strong>{v}</strong><span>{l}</span></article>)}</div>
<div className="section-heading"><h3>Próximos serviços</h3><Link href="/agenda">Ver agenda</Link></div>{agenda.length===0?<p className="muted">Nenhum serviço agendado.</p>:<div className="agenda-list">{agenda.map(x=><Link href="/servicos" className="agenda-card" key={x.id}><div className="time-pill">{x.hora_agendada||"—"}</div><div className="agenda-main"><strong>{nome(x.cliente_id)}</strong><span>{x.tipo_servico}</span></div><span className="status-badge">{x.status}</span></Link>)}</div>}
<section className="quick-card"><div><p className="eyebrow">ATALHO</p><h3>Recebeu uma nova solicitação?</h3><p>Abra um chamado e organize o atendimento.</p></div><Link href="/chamados/novo" className="round-plus">+</Link></section></div>}
