"use client"; import Link from "next/link"; import {useEffect,useState} from "react"; import {addStore,nextNumber,readStore,updateStore} from "@/lib/local-store"; import {useRouter} from "next/navigation"; import {fmtData} from "@/lib/domain";
export default function Servicos(){const r=useRouter();const [ch,setCh]=useState<any[]>([]);const [ord,setOrd]=useState<any[]>([]);const [clientes,setClientes]=useState<any[]>([]);
function load(){setCh(readStore("chamados"));setOrd(readStore("ordens"));setClientes(readStore("clientes"))} useEffect(load,[]);
function nome(id:string){const c=clientes.find(x=>x.id===id);return c?.nome_fantasia||c?.nome||"Cliente"}
function iniciar(c:any){const os={id:crypto.randomUUID(),numero:nextNumber("ordens"),chamado_id:c.id,cliente_id:c.cliente_id,local_id:c.local_id,equipamento_id:c.equipamento_id,tipo_servico:c.tipo_servico,status:"em_atendimento",inicio:new Date().toISOString(),diagnostico:"",servico_executado:"",situacao_final:"",recomendacoes:"",pendencias:"",observacoes:"",valor_servico:0,forma_pagamento:""};addStore("ordens",os);updateStore("chamados",{...c,status:"em_atendimento"});r.push(`/os/${os.id}`)}
return <div className="page"><header className="simple-header"><div><p className="eyebrow">RM ASSIST</p><h1>Serviços</h1><p>Chamados e ordens de serviço.</p></div><Link href="/chamados/novo" className="primary-button">+ Novo chamado</Link></header>
<h3 className="form-section-title">Chamados</h3>{ch.length===0?<p className="muted">Nenhum chamado.</p>:<div className="service-list">{ch.map(c=><article className="service-card" key={c.id}><div><span className={`status-chip ${c.status}`}>{c.status.replace("_"," ")}</span><h3>Chamado #{String(c.numero).padStart(4,"0")} — {nome(c.cliente_id)}</h3><p>{c.descricao}</p><small>{c.data_agendada?`${fmtData(c.data_agendada)} • ${c.hora_agendada}`:"Sem agendamento"} • {c.prioridade}</small></div>{["aberto","agendado"].includes(c.status)&&<button className="primary-button" onClick={()=>iniciar(c)}>Iniciar atendimento</button>}</article>)}</div>}
<h3 className="form-section-title">Ordens de serviço</h3>{ord.length===0?<p className="muted">Nenhuma OS.</p>:<div className="service-list">{ord.map(o=><Link href={`/os/${o.id}`} className="service-card" key={o.id}><div><span className={`status-chip ${o.status}`}>{o.status.replace("_"," ")}</span><h3>OS #{String(o.numero).padStart(4,"0")} — {nome(o.cliente_id)}</h3><p>{o.tipo_servico}</p></div><span className="chevron">›</span></Link>)}</div>}
</div>}
